// https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

#ifndef ANSI_COLOR_CODE_H_
#define ANSI_COLOR_CODE_H_

#define ANSI_COLOR_RED "\x1b[31m"
#define ANSI_COLOR_GREEN "\x1b[32m"
#define ANSI_COLOR_YELLOW "\x1b[33m"
#define ANSI_COLOR_BLUE "\x1b[34m"
#define ANSI_COLOR_MAGENTA "\x1b[35m"
#define ANSI_COLOR_CYAN "\x1b[36m"
#define ANSI_COLOR_WHITE "\x1b[37m"
#define ANSI_COLOR_RESET "\x1b[0m"
#define ANSI_COLOR_BRIGHT_RED "\x1b[91m"
#define ANSI_COLOR_BRIGHT_GREEN "\x1b[92m"
#define ANSI_COLOR_BRIGHT_YELLOW "\x1b[93m"
#define ANSI_COLOR_BRIGHT_BLUE "\x1b[94m"
#define ANSI_COLOR_BRIGHT_MAGENTA "\x1b[95m"
#define ANSI_COLOR_BRIGHT_CYAN "\x1b[96m"

#define ANSI_COLOR_RED_REGION(__c_str) ANSI_COLOR_RED __c_str ANSI_COLOR_RESET
#define ANSI_COLOR_GREEN_REGION(__c_str) ANSI_COLOR_GREEN __c_str ANSI_COLOR_RESET
#define ANSI_COLOR_YELLOW_REGION(__c_str) ANSI_COLOR_YELLOW __c_str ANSI_COLOR_RESET
#define ANSI_COLOR_BLUE_REGION(__c_str) ANSI_COLOR_BLUE __c_str ANSI_COLOR_RESET
#define ANSI_COLOR_MAGENTA_REGION(__c_str) ANSI_COLOR_MAGENTA __c_str ANSI_COLOR_RESET
#define ANSI_COLOR_CYAN_REGION(__c_str) ANSI_COLOR_CYAN __c_str ANSI_COLOR_RESET
#define ANSI_COLOR_WHITE_REGION(__c_str) ANSI_COLOR_WHITE __c_str ANSI_COLOR_RESET
#define ANSI_COLOR_BRIGHT_RED_REGION(__c_str) ANSI_COLOR_BRIGHT_RED __c_str ANSI_COLOR_RESET
#define ANSI_COLOR_BRIGHT_GREEN_REGION(__c_str) ANSI_COLOR_BRIGHT_GREEN __c_str ANSI_COLOR_RESET
#define ANSI_COLOR_BRIGHT_YELLOW_REGION(__c_str) ANSI_COLOR_BRIGHT_YELLOW __c_str ANSI_COLOR_RESET
#define ANSI_COLOR_BRIGHT_BLUE_REGION(__c_str) ANSI_COLOR_BRIGHT_BLUE __c_str ANSI_COLOR_RESET
#define ANSI_COLOR_BRIGHT_MAGENTA_REGION(__c_str) ANSI_COLOR_BRIGHT_MAGENTA __c_str ANSI_COLOR_RESET
#define ANSI_COLOR_BRIGHT_CYAN_REGION(__c_str) ANSI_COLOR_BRIGHT_CYAN __c_str ANSI_COLOR_RESET

#define ANSI_COLOR_RED_STR(__str) (ANSI_COLOR_RED + __str + ANSI_COLOR_RESET)
#define ANSI_COLOR_GREEN_STR(__str) (ANSI_COLOR_GREEN + __str + ANSI_COLOR_RESET)
#define ANSI_COLOR_YELLOW_STR(__str) (ANSI_COLOR_YELLOW + __str + ANSI_COLOR_RESET)
#define ANSI_COLOR_BLUE_STR(__str) (ANSI_COLOR_BLUE + __str + ANSI_COLOR_RESET)
#define ANSI_COLOR_MAGENTA_STR(__str) (ANSI_COLOR_MAGENTA + __str + ANSI_COLOR_RESET)
#define ANSI_COLOR_CYAN_STR(__str) (ANSI_COLOR_CYAN + __str + ANSI_COLOR_RESET)
#define ANSI_COLOR_WHITE_STR(__str) (ANSI_COLOR_WHITE + __str + ANSI_COLOR_RESET)
#define ANSI_COLOR_BRIGHT_RED_STR(__str) (ANSI_COLOR_BRIGHT_RED + __str + ANSI_COLOR_RESET)
#define ANSI_COLOR_BRIGHT_GREEN_STR(__str) (ANSI_COLOR_BRIGHT_GREEN + __str + ANSI_COLOR_RESET)
#define ANSI_COLOR_BRIGHT_YELLOW_STR(__str) (ANSI_COLOR_BRIGHT_YELLOW + __str + ANSI_COLOR_RESET)
#define ANSI_COLOR_BRIGHT_BLUE_STR(__str) (ANSI_COLOR_BRIGHT_BLUE + __str + ANSI_COLOR_RESET)
#define ANSI_COLOR_BRIGHT_MAGENTA_STR(__str) (ANSI_COLOR_BRIGHT_MAGENTA + __str + ANSI_COLOR_RESET)
#define ANSI_COLOR_BRIGHT_CYAN_STR(__str) (ANSI_COLOR_BRIGHT_CYAN + __str + ANSI_COLOR_RESET)

#endif