#Master 설정 정보
master:
  master_id: 100
  dcf_txt: "generated/plutools_qd/master.dcf"
  interface_name: "can0"

# 드라이버 설정 정보
drivers:
  - driver_id: 1
    eds_path: "driver/eds/plutools/FDK_PMSM_SIEMENS-VSXXDXX-A-20240203_V1.eds"
    binary_path: "generated/plutools_qd/slave_1.bin"
    sdo_timeout: 300 # ms

  - driver_id: 2
    eds_path: "driver/eds/plutools/FDK_PMSM_SIEMENS-VSXXDXX-A-20240203_V1.eds"
    binary_path: "generated/plutools_qd/slave_2.bin"
    sdo_timeout: 300 # ms

  - driver_id: 3
    eds_path: "driver/eds/plutools/FDK_PMSM_SIEMENS-VSXXDXX-A-20240203_V1.eds"
    binary_path: "generated/plutools_qd/slave_3.bin"
    sdo_timeout: 300 # ms

  - driver_id: 4
    eds_path: "driver/eds/plutools/FDK_PMSM_SIEMENS-VSXXDXX-A-20240203_V1.eds"
    binary_path: "generated/plutools_qd/slave_4.bin"
    sdo_timeout: 300 # ms

# 모터 설정 정보
motors:
  - motor_id: 0
    driver_id: 1
    motor_driver: "default"
    multiaxis_index: 0
    mode_of_operation: 3
    ratio: 28
    ppr: 10000

  - motor_id: 3
    driver_id: 2
    motor_driver: "default"
    multiaxis_index: 0
    mode_of_operation: 3
    ratio: 28
    ppr: 10000

  - motor_id: 4
    driver_id: 3
    motor_driver: "default"
    multiaxis_index: 0
    mode_of_operation: 3
    ratio: 28
    ppr: 10000

  - motor_id: 7
    driver_id: 4
    motor_driver: "default"
    multiaxis_index: 0
    mode_of_operation: 3
    ratio: 28
    ppr: 10000

motor_extra_info:
  - motor_id: 0
    voltage: 
      index: 0x2003
      subindex: 0x00
      type: "int16_t"
      multiplier: 0.1
    current:
      index: 0x6078
      subindex: 0x00
      type: "int16_t"
      multiplier: 0.1
    error:
      index: 0x603f
      subindex: 0x00
      type: "uint16_t"
      codes:
        - { value: 0x0001, message: "Power undervoltage" }
        - { value: 0x0002, message: "Motor position error" }
        - { value: 0x0004, message: "Feedback error" }
        - { value: 0x0008, message: "Motor overcurrent" }
        - { value: 0x0010, message: "Motor overload" }
        - { value: 0x0020, message: "EEPROM error" }
        - { value: 0x0040, message: "IGBT fault" }
        - { value: 0x0080, message: "Driver overtemperature" }
        - { value: 0x0100, message: "Motor phase loss" }
        - { value: 0x0200, message: "Motor current deviation" }
        - { value: 0x0400, message: "Motor speed deviation" }
        - { value: 0x0800, message: "Motor overtemperature" }
        - { value: 0x1000, message: "Power overvoltage" }
        - { value: 0x2000, message: "ABS communication error" }
        - { value: 0x4000, message: "Brake error" }
        - { value: 0x8000, message: "Latch" }

  - motor_id: 3
    voltage: 
      index: 0x2003
      subindex: 0x00
      type: "int16_t"
      multiplier: 0.1
    current:
      index: 0x6078
      subindex: 0x00
      type: "int16_t"
      multiplier: 0.1
    error:
      index: 0x603f
      subindex: 0x00
      type: "uint16_t"
      codes:
        - { value: 0x0001, message: "Power undervoltage" }
        - { value: 0x0002, message: "Motor position error" }
        - { value: 0x0004, message: "Feedback error" }
        - { value: 0x0008, message: "Motor overcurrent" }
        - { value: 0x0010, message: "Motor overload" }
        - { value: 0x0020, message: "EEPROM error" }
        - { value: 0x0040, message: "IGBT fault" }
        - { value: 0x0080, message: "Driver overtemperature" }
        - { value: 0x0100, message: "Motor phase loss" }
        - { value: 0x0200, message: "Motor current deviation" }
        - { value: 0x0400, message: "Motor speed deviation" }
        - { value: 0x0800, message: "Motor overtemperature" }
        - { value: 0x1000, message: "Power overvoltage" }
        - { value: 0x2000, message: "ABS communication error" }
        - { value: 0x4000, message: "Brake error" }
        - { value: 0x8000, message: "Latch" }

  - motor_id: 4
    voltage: 
      index: 0x2003
      subindex: 0x00
      type: "int16_t"
      multiplier: 0.1
    current:
      index: 0x6078
      subindex: 0x00
      type: "int16_t"
      multiplier: 0.1
    error:
      index: 0x603f
      subindex: 0x00
      type: "uint16_t"
      codes:
        - { value: 0x0001, message: "Power undervoltage" }
        - { value: 0x0002, message: "Motor position error" }
        - { value: 0x0004, message: "Feedback error" }
        - { value: 0x0008, message: "Motor overcurrent" }
        - { value: 0x0010, message: "Motor overload" }
        - { value: 0x0020, message: "EEPROM error" }
        - { value: 0x0040, message: "IGBT fault" }
        - { value: 0x0080, message: "Driver overtemperature" }
        - { value: 0x0100, message: "Motor phase loss" }
        - { value: 0x0200, message: "Motor current deviation" }
        - { value: 0x0400, message: "Motor speed deviation" }
        - { value: 0x0800, message: "Motor overtemperature" }
        - { value: 0x1000, message: "Power overvoltage" }
        - { value: 0x2000, message: "ABS communication error" }
        - { value: 0x4000, message: "Brake error" }
        - { value: 0x8000, message: "Latch" }

  - motor_id: 7
    voltage: 
      index: 0x2003
      subindex: 0x00
      type: "int16_t"
      multiplier: 0.1
    current:
      index: 0x6078
      subindex: 0x00
      type: "int16_t"
      multiplier: 0.1
    error:
      index: 0x603f
      subindex: 0x00
      type: "uint16_t"
      codes:
        - { value: 0x0001, message: "Power undervoltage" }
        - { value: 0x0002, message: "Motor position error" }
        - { value: 0x0004, message: "Feedback error" }
        - { value: 0x0008, message: "Motor overcurrent" }
        - { value: 0x0010, message: "Motor overload" }
        - { value: 0x0020, message: "EEPROM error" }
        - { value: 0x0040, message: "IGBT fault" }
        - { value: 0x0080, message: "Driver overtemperature" }
        - { value: 0x0100, message: "Motor phase loss" }
        - { value: 0x0200, message: "Motor current deviation" }
        - { value: 0x0400, message: "Motor speed deviation" }
        - { value: 0x0800, message: "Motor overtemperature" }
        - { value: 0x1000, message: "Power overvoltage" }
        - { value: 0x2000, message: "ABS communication error" }
        - { value: 0x4000, message: "Brake error" }
        - { value: 0x8000, message: "Latch" }