R2000:
  transport: "tcp"
  scanner_ip: "10.0.10.9"
  device: "R2000"
  start_angle: -1800000
  max_num_points_scan: 0
  packet_type: "B"
  scan_topic: "/scan_front"
  watchdogtimeout: 60000
  watchdog: true
