bool safety_check_and_reset_req          # 안전 확인 및 리셋 요청
bool bumper_check                        # 범퍼 상태 확인
bool auto_mode                           # 자동 모드 활성화 여부
bool manual_mode                         # 수동 모드 활성화 여부
bool initial_switch                      # 초기화 스위치 상태
bool orgo_lift_top_position              # 오르고 리프트 상단 위치
bool orgo_lift_bottom_position           # 오르고 리프트 하단 위치
bool orgo_lift_overload                  # 오르고 리프트 과부하
bool orgo_lift_error                     # 오르고 리프트 오류 상태
bool orgo_lift_run_stop                  # 오르고 리프트 동작 정지
bool manual_lift_up_switch               # 수동 리프트 상승 스위치
bool manual_lift_down_switch             # 수동 리프트 하강 스위치
bool job_cancel_switch                   # 작업 취소 스위치 상태
bool pc_fan_run_check                    # PC 팬 작동 여부
bool manual_charge_port_insert_check     # 수동 충전 포트 확인
bool work_check_sensor                   # 작업 확인 센서 상태