# ===============================
#  LCCS Parameter Map
# ===============================

# 100 이상 일 경우 LCCS off
LCCS:
  default: [0.5,0.5,0.5,0.5]
  0: [0,0,0,0]
  1: [0.5,0.5,0.5,0.5]
  2: [1.0,1.0,1.0,1.0]
  3: [0.5,0.5,0.5,0.5]
  4: [0,0,0,0]
  5: [0,0,0,0]
  100: [0,0,0,0]
  101: [0.5,0.5,0.5,0.5]